volumes:
  media_volume:
  static_volume:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env.prod

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file: .env.prod
    # mount shared static_volume to container's /app/build
    volumes:
      - static_volume:/app/build
    stdin_open: true

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file: .env.prod
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/mnt/media
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
    # copy nginx's conf file
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media_volume:/mnt/media
    # mount shared static_volume to /mnt/static
      - static_volume:/mnt/static
    depends_on:
      - backend
