version: '3.3'

volumes:
  media:
  static:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    image: onixsofi/foodgram_backend
    env_file: .env
    volumes:
      - media:/app/media/
      - static:/static/
    depends_on:
      - db
  frontend:
    image: onixsofi/foodgram_frontend
    env_file: .env
    # command: cp -r /app/build/. /static/
    volumes:
      - static:/result_build/
    depends_on:
      - backend
  proxy:
    image: nginx:1.25.4-alpine
    ports:
      - 9500:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media:/media/
      - static:/static/
    depends_on:
      - frontend