volumes:
  media_volume:
  static_volume:
  pg_data:

networks:
  webapp:
    bridge

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env.prod
    networks:
      - webapp

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file: .env.prod
    stdin_open: true
    networks:
      - webapp

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/vol/media
      - static_volume:/vol/collected_static  # Mount static volume
    depends_on:
      - db
    networks:
      - webapp

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro      # Mount React build files
      - media_volume:/vol/media
      - static_volume:/vol/collected_static:ro         # Mount static files
    depends_on:
      - backend
    networks:
      - webapp
