name: Main foodgram workflow
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          sudo su
          rm -rf foodgram/
          git clone https://github.com/Christina-Gordiichuk/foodgram/
          cd foodgram/
          docker system prune -a --force
          npm cache clean --force
          apt-get clean
          journalctl --vacuum-size=100M
          journalctl --vacuum-time=1d
          journalctl --vacuum-files=10
          docker compose -f docker-compose.yml up --build
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Деплой успешно выполнен!
